# Generated by Django 2.2.7 on 2019-11-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('Unique_Squirrel_ID', models.CharField(max_length=100)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('Date', models.IntegerField(default=0)),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=100)),
                ('Primary_Fur_Color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], max_length=100)),
                ('Location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Gound')], max_length=100)),
                ('Specific_Location', models.CharField(max_length=100)),
                ('Running', models.BooleanField(default='False')),
                ('Chasing', models.BooleanField(default='False')),
                ('Climbing', models.BooleanField(default='False')),
                ('Eating', models.BooleanField(default='False')),
                ('Foraging', models.BooleanField(default='False')),
                ('Other_Activities', models.CharField(max_length=100)),
                ('Kuks', models.BooleanField(default='False')),
                ('Quass', models.BooleanField(default='False')),
                ('Moans', models.BooleanField(default='False')),
                ('Tail_flags', models.BooleanField(default='False')),
                ('Tail_twitches', models.BooleanField(default='False')),
                ('Approaches', models.BooleanField(default='False')),
                ('Indifferent', models.BooleanField(default='False')),
                ('Runs_from', models.BooleanField(default='False')),
            ],
        ),
    ]
