# Generated by Django 2.2.7 on 2019-11-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sightings',
            old_name='Quass',
            new_name='Quaas',
        ),
    ]
